mealアプリ課題完了
nn12vl9l/meal_app pull request #1
Opened 2021-10-13 11:22 UTC by nn12vl9l

2021-10-13 12:33 UTC, nn12vl9l commented
<img width="1440" alt="一覧画面" src="https://user-images.githubusercontent.com/64241250/137132801-b272311a-1c9d-41b1-b353-db3c453168be.png">
<img width="1440" alt="登録画面" src="https://user-images.githubusercontent.com/64241250/137132826-6d1417d3-d96a-4b50-83e3-b8a0a61d6644.png">
<img width="1440" alt=" 照会画面" src="https://user-images.githubusercontent.com/64241250/137132827-f0bbdaa0-ac87-491b-ba24-45f523a747b3.png">
<img width="1440" alt="記事削除(メッセージ)" src="https://user-images.githubusercontent.com/64241250/137132835-d50df59d-4cb4-4659-8f29-2c386b325e11.png">
<img width="1440" alt="お気に入り登録" src="https://user-images.githubusercontent.com/64241250/137132839-d14b5353-cb5b-4e6c-9412-e7edaecc9380.png">
<img width="1440" alt="別ユーザーの照会画面" src="https://user-images.githubusercontent.com/64241250/137132844-cbfcf861-91cc-4383-8ccb-7d0664eab595.png">
![Uploading 編集画面.png…]()

2021-10-13 21:19 UTC, kazu-taka requested changes
@nn12vl9l 
コメントしたので確認お願いします🙏

2021-10-13 21:19 UTC, kazu-taka commented on app/Http/Controllers/LikeController.php
> +        $user = Auth::user()->id;
@nn12vl9l 
$userだとユーザー情報が全てセットされているイメージになるので、$user_idの方がいいと思います！

2021-10-13 21:19 UTC, kazu-taka commented on resources/views/posts/show.blade.php
> +            <p class="text-sm mb-2 md:text-base font-normal text-gray-800">{{ $post->date_diff }} 前に投稿</p>
@nn12vl9l 
他の方にも今聞いてますが、`date_diff`はPHP標準のdate_diffではなさそうですが、何かのライブラリですか！？✨

2021-10-13 23:41 UTC, nn12vl9l commented on resources/views/posts/show.blade.php
> +            <p class="text-sm mb-2 md:text-base font-normal text-gray-800">{{ $post->date_diff }} 前に投稿</p>
お疲れ様です💦
postモデルにアクセサを追加して呼び出しているというイメージでした。

2021-10-14 00:03 UTC, kazu-taka commented on resources/views/posts/show.blade.php
> +            <p class="text-sm mb-2 md:text-base font-normal text-gray-800">{{ $post->date_diff }} 前に投稿</p>
@nn12vl9l 
ありがとうございます！
完全にモデル見逃してました🙇‍♂️

2021-10-14 00:03 UTC, kazu-taka commented
@nn12vl9l 
問題ないのでマージしてOKです！！
![LGTM](https://image.lgtmoon.dev/69652)

2021-10-14 00:06 UTC, merged